import { FishSpecies, RarityConfig, RarityTier } from './types.js';

export const RARITY_CONFIGS: Record<RarityTier, RarityConfig> = {
  1: {
    tier: 1,
    label: 'Muito Comum',
    probability: 0.40,
    percentage: 40,
    color: '#94a3b8',       // Cinza claro metálico
    glowColor: '#cbd5e1',
    badgeBg: 'rgba(148, 163, 184, 0.2)',
    typicalWeightRange: '50g a 250g',
    stars: '★☆☆☆☆☆',
  },
  2: {
    tier: 2,
    label: 'Comum',
    probability: 0.25,
    percentage: 25,
    color: '#22c55e',       // Verde esmeralda
    glowColor: '#4ade80',
    badgeBg: 'rgba(34, 197, 94, 0.2)',
    typicalWeightRange: '300g a 1.2kg',
    stars: '★★☆☆☆☆',
  },
  3: {
    tier: 3,
    label: 'Incomum',
    probability: 0.18,
    percentage: 18,
    color: '#0ea5e9',       // Azul oceano
    glowColor: '#38bdf8',
    badgeBg: 'rgba(14, 165, 233, 0.2)',
    typicalWeightRange: '1.5kg a 5.0kg',
    stars: '★★★☆☆☆',
  },
  4: {
    tier: 4,
    label: 'Raro',
    probability: 0.10,
    percentage: 10,
    color: '#a855f7',       // Roxo místico
    glowColor: '#c084fc',
    badgeBg: 'rgba(168, 85, 247, 0.2)',
    typicalWeightRange: '2.0kg a 7.0kg',
    stars: '★★★★☆☆',
  },
  5: {
    tier: 5,
    label: 'Épico',
    probability: 0.05,
    percentage: 5,
    color: '#f59e0b',       // Dourado âmbar
    glowColor: '#fbbf24',
    badgeBg: 'rgba(245, 158, 11, 0.25)',
    typicalWeightRange: '6.0kg a 16.0kg',
    stars: '★★★★★☆',
  },
  6: {
    tier: 6,
    label: 'Lendário',
    probability: 0.02,
    percentage: 2,
    color: '#ef4444',       // Vermelho carmesim brilhante
    glowColor: '#f87171',
    badgeBg: 'rgba(239, 68, 68, 0.3)',
    typicalWeightRange: '25.0kg a 120.0kg',
    stars: '★★★★★★',
  },
};

export const FISH_SPECIES_CATALOG: FishSpecies[] = [
  // Nível 1 - Muito Comum (Faixa: 50g a 250g)
  {
    id: 'lambari',
    name: 'Lambari',
    rarity: 1,
    minWeight: 50,
    maxWeight: 150,
    description: 'Um peixe pequeno e veloz dos riachos e margens tranquilas.',
    baseColor: '#94a3b8',
    accentColor: '#cbd5e1',
    finColor: '#fca5a5',
    bodyLengthRatio: 1.0,
  },
  {
    id: 'piaba',
    name: 'Piaba',
    rarity: 1,
    minWeight: 60,
    maxWeight: 180,
    description: 'Muito arisco, nada em cardumes saltitando à tona da água.',
    baseColor: '#a1a1aa',
    accentColor: '#f4f4f5',
    finColor: '#fde047',
    bodyLengthRatio: 0.95,
  },
  {
    id: 'acara',
    name: 'Acará',
    rarity: 1,
    minWeight: 80,
    maxWeight: 250,
    description: 'Peixe arredondado e resistente, com escamas rajadas.',
    baseColor: '#78716c',
    accentColor: '#d6d3d1',
    finColor: '#fdba74',
    bodyLengthRatio: 0.8,
  },

  // Nível 2 - Comum (Faixa: 300g a 1.2kg)
  {
    id: 'tilapia',
    name: 'Tilápia',
    rarity: 2,
    minWeight: 400,
    maxWeight: 1200,
    description: 'Muito prolífica e saborosa, com barbatanas listradas.',
    baseColor: '#15803d',
    accentColor: '#4ade80',
    finColor: '#86efac',
    bodyLengthRatio: 1.1,
  },
  {
    id: 'pacu_pequeno',
    name: 'Pacu Pequeno',
    rarity: 2,
    minWeight: 300,
    maxWeight: 1000,
    description: 'Famoso por sua mandíbula forte e corpo roliço e achatado.',
    baseColor: '#166534',
    accentColor: '#bbf7d0',
    finColor: '#f97316',
    bodyLengthRatio: 0.9,
  },

  // Nível 3 - Incomum (Faixa: 1.5kg a 5.0kg)
  {
    id: 'carpa_espelho',
    name: 'Carpa-espelho',
    rarity: 3,
    minWeight: 2000,
    maxWeight: 5000,
    description: 'Possui escamas largas e espelhadas que reluzem na luz.',
    baseColor: '#0369a1',
    accentColor: '#38bdf8',
    finColor: '#7dd3fc',
    bodyLengthRatio: 1.25,
  },
  {
    id: 'bagre',
    name: 'Bagre',
    rarity: 3,
    minWeight: 1500,
    maxWeight: 4500,
    description: 'Habitante do fundo dos rios com longos barbilhões sensoriais.',
    baseColor: '#1e3a8a',
    accentColor: '#60a5fa',
    finColor: '#93c5fd',
    bodyLengthRatio: 1.35,
  },

  // Nível 4 - Raro (Faixa: 2.0kg a 7.0kg)
  {
    id: 'truta_arco_iris',
    name: 'Truta Arco-Íris',
    rarity: 4,
    minWeight: 2000,
    maxWeight: 6500,
    description: 'Predadora de águas geladas com uma faixa rosada cintilante.',
    baseColor: '#6b21a8',
    accentColor: '#c084fc',
    finColor: '#f472b6',
    bodyLengthRatio: 1.3,
  },
  {
    id: 'black_bass',
    name: 'Black Bass',
    rarity: 4,
    minWeight: 2200,
    maxWeight: 7000,
    description: 'Excelente caçador com bote agressivo e grande força na linha.',
    baseColor: '#581c87',
    accentColor: '#a855f7',
    finColor: '#34d399',
    bodyLengthRatio: 1.2,
  },

  // Nível 5 - Épico (Faixa: 6.0kg a 16.0kg)
  {
    id: 'dourado',
    name: 'Dourado',
    rarity: 5,
    minWeight: 6000,
    maxWeight: 15000,
    description: 'Conhecido como o "Rei do Rio", salta acrobaticamente ao ser fisgado.',
    baseColor: '#b45309',
    accentColor: '#fbbf24',
    finColor: '#f59e0b',
    bodyLengthRatio: 1.45,
  },
  {
    id: 'tucunare_acu',
    name: 'Tucunaré-Açu',
    rarity: 5,
    minWeight: 6500,
    maxWeight: 16000,
    description: 'Gigante amazônico com um marcante ocelo caudal e cores vibrantes.',
    baseColor: '#d97706',
    accentColor: '#fcd34d',
    finColor: '#ea580c',
    bodyLengthRatio: 1.4,
  },

  // Nível 6 - Lendário (Faixa: 25.0kg a 120.0kg)
  {
    id: 'pirarucu_gigante',
    name: 'Pirarucu Gigante',
    rarity: 6,
    minWeight: 35000,
    maxWeight: 120000,
    description: 'O monstro da Amazônia, com escamas duras como armaduras avermelhadas.',
    baseColor: '#991b1b',
    accentColor: '#f87171',
    finColor: '#ef4444',
    bodyLengthRatio: 1.7,
  },
  {
    id: 'jau',
    name: 'Jaú',
    rarity: 6,
    minWeight: 25000,
    maxWeight: 90000,
    description: 'Um dos maiores bagres das bacias fluviais, um verdadeiro colosso das profundezas.',
    baseColor: '#7f1d1d',
    accentColor: '#ef4444',
    finColor: '#451a03',
    bodyLengthRatio: 1.6,
  },
];

export const SPECIES_BY_RARITY: Record<RarityTier, FishSpecies[]> = {
  1: FISH_SPECIES_CATALOG.filter((f) => f.rarity === 1),
  2: FISH_SPECIES_CATALOG.filter((f) => f.rarity === 2),
  3: FISH_SPECIES_CATALOG.filter((f) => f.rarity === 3),
  4: FISH_SPECIES_CATALOG.filter((f) => f.rarity === 4),
  5: FISH_SPECIES_CATALOG.filter((f) => f.rarity === 5),
  6: FISH_SPECIES_CATALOG.filter((f) => f.rarity === 6),
};
